version: '3.9'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
#     volumes:
#       - db_volume:/var/lib/postgresql/data

# volumes:
#   db_volume:
